### ISSUE TITLE
Babylon preview: 'loadAsset of unknown' error

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/gltf-vscode#125]
Hi folks!

I am encountering the following issue with a pretty simple model: The model is displayed nicely in the Cesium and Three previewers, however, the following error pops up using the Babylon engine:

![babylon_loadasset_error](https://user-images.githubusercontent.com/15689124/48318121-08629d80-e5fc-11e8-9dc0-113c9e8af39c.png)

I updated to the recently released version 2.1.17 and use the 'import from GLB' with this model ([morph02.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/2569829/morph02.zip)). The model itself should be fine (validator has no problems and the babylon [sandcastle](https://sandbox.babylonjs.com/) displays it nicely).

Any ideas why Babylon fails? Thank you!

**Comment by emackey** [comment]
I can reproduce this easily enough.  Haven't figured out why yet.

Did this model used to work with the previous version of this plugin?

**Comment by tkazik** [comment]
@emackey Thx for the quick reply! 
The previous version also had the same issue with this model.
I tested a few more models and the preview failed for all models exported with the 3ds max - babylon - exporter. So it might be related to that...on the other hand, the online sandcastle-viewer of babylon displays all the model correctly.

**Comment by emackey** [comment]
/cc @bghgary Do you have any advice here?  I don't know my way around the inside of Babylon too well, but I'm trying to step through with the debugger.  When loading the problem model, I end up in here:

https://github.com/BabylonJS/Babylon.js/blob/v3.3.0/src/Loading/Plugins/babylon.babylonFileLoader.ts#L62

```
            // Animations
            if (parsedData.animations !== undefined && parsedData.animations !== null) {
                for (index = 0, cache = parsedData.animations.length; index < cache; index++) {
                    var parsedAnimation = parsedData.animations[index];
                    var animation = Animation.Parse(parsedAnimation);
```

This "parsedAnimation" thing at this point seems to be a raw copy of the animation definition from the glTF file.  It has `channels`, `name`, `samplers`, just like a proper glTF animation, but doesn't look Babylon-specific.  And then it calls `Animation.Parse`:

https://github.com/BabylonJS/Babylon.js/blob/v3.3.0/src/Animations/babylon.animation.ts#L1136

```
       /**
         * Parses an animation object and creates an animation
         * @param parsedAnimation Parsed animation object
         * @returns Animation object
         */
        public static Parse(parsedAnimation: any): Animation {
            var animation = new Animation(parsedAnimation.name, parsedAnimation.property, parsedAnimation.framePerSecond, parsedAnimation.dataType, parsedAnimation.loopBehavior);
```

In here, clearly it was expecting something Babylon-specific.  It wants `name`, `property`, `framePerSecond`, etc.  It was not expecting raw glTF stuff coming down in here.

`Parse` then calls the constructor, which dies here:

https://github.com/BabylonJS/Babylon.js/blob/v3.3.0/src/Animations/babylon.animation.ts#L486

```
    this.targetPropertyPath = targetProperty.split(".");
```

Because of the type mismatch, `targetPropertyPath` is undefined, and `split` crashes.

The error is caught in `loadAssets`, but the error handler gets confused by the same animation's type mismatch, and ends up writing a message about "unknown."

**Comment by emackey** [comment]
FYI I'm loading the glTF data directly as the scene, like this:

https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/2.1.17/pages/babylonView.js#L76

```
    BABYLON.SceneLoader.Append(rootPath, 'data:' + gltfContent, scene, function() {
```

**Comment by bghgary** [comment]
Yeah, I know exactly why it's doing this and I have a fix locally along with a bunch of other changes, but I don't have a PR ready for this yet. I can try to split this part out, but I'm not sure it's worth it.
