### ISSUE TITLE
Context menu tree does not show all options in v2.3.13 Mac 

### ISSUE THREAD

**Issue by rohan-percept** [AnalyticalGraphicsInc/gltf-vscode#230]
Attaching ref images below - 

On 2.3.12 -

<img width="403" alt="Screenshot 2021-12-06 at 15 07 00" src="https://user-images.githubusercontent.com/64609221/144870014-00ce06df-1b74-4266-a919-aadb9d8fec95.png">

On 2.3.13 - 
 
<img width="476" alt="Screenshot 2021-12-06 at 14 45 08" src="https://user-images.githubusercontent.com/64609221/144870106-7d08a6cb-d22d-45a3-a0d0-0890dd2ae602.png">

Basically, I can open preview window with 'option + G' combo, but not via the context menu

System - M1 MacBook Air (2020)
OS - Mac OS Monterey 12.1
VSCode - v1.62.3

**Comment by emackey** [comment]
Hi.  Some of these options were intentionally moved in 2.3.13.  The right-click on the title bar is really for options that apply to the entire file, such as export to GLB and validating the whole file.  As a result, these few remaining options now work on **all** the open glTF files across the set of open tabs, not just the active tab.

The options that apply to a particular spot in the text, such as the Data URI converters, are now on the context menu for the body of the file instead of the title.  "Preview" had to move there too, as it only works for the currently active file, not all open tabs.

Several options became available in the file explorer tree.  Things like importing from GLB files are in that context menu now, and they only reveal themselves if you right-click the appropriate file type.  These options no longer need that file to be loaded into any editor in order to work correctly.

As always, you can manually run any command from the command bar.  This is `F1` on the PC, but I don't know what it is on Mac, possibly the same key.  Type `gltf` into that command bar and it should present the full list of commands.
