### ISSUE TITLE
Add full glTF Validator integration

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/gltf-vscode#27]
I talked briefly with @lexaknyazev about this at the glTF roadmap meeting after SIGGRAPH 2017.  Basically, this extension is using VSCode's built-in JSON validator against the glTF schema, but there are lots (dozens, hundreds?) of types of glTF errors (such as binary range out-of-bounds, etc) that can't be caught by simple JSON schema validation alone.  To catch these, we should instead run the official [glTF Validator from Khronos](https://github.com/KhronosGroup/glTF-Validator).

The official validator is written in Dart, and I believe has already been compiled to JS.  @lexaknyazev mentioned that an npm package was going to be released soon, and that we could include that as a dependency.

Letting go of VSCode's JSON validation and switching to a custom validator will have some complexity on the VSCode integration side as well.  I've looked into it, but it's not immediately clear to me the best path forward.  @balefrost expressed some interest, but doesn't have any time to work on this last I checked.

Contributions here are most welcome!

**Comment by emackey** [comment]
Someday it would be great to run validation as part of a custom glTF Language Server.

https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol

https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by lexaknyazev** [comment]
@emackey 
First-glance thoughts on steps needed to implement this:
- find a way to resolve [JSON Pointer (RFC 6901)](https://tools.ietf.org/html/rfc6901) references from validation output to line numbers/positions;
- tweak validation output structure to better fit [LSP Diagnostic](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#diagnostic) object.

**Comment by emackey** [comment]
On that first point, this extension already [depends](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/cb3092cacb13222a17e359dbfdfa52834dbc16db/package.json#L125) on an npm package called [json-source-map](https://www.npmjs.com/package/json-source-map), and we [use it](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/cb3092cacb13222a17e359dbfdfa52834dbc16db/src/extension.ts#L50) to get a JSON pointer to a data-URI that the user has clicked on in the text editor.

**Comment by emackey** [comment]
I got a first cut of this working last night on the `validator-preview` branch.  I'm still treating glTF as `json` language, but I've added my own language server in addition to the JSON one, and I now have actual output from the validator flowing into the document diagnostics mechanism.

**Comment by lexaknyazev** [comment]
Since both VS Code glTF Server and glTF Validator JS API are in pre-release stage, let's establish best practices for their integration.

Here're my first comments on [server.ts](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/075d6608a6b39a063f5e7cb329b94da52414f82a/server/src/server.ts) as of 075d6608a6b39a063f5e7cb329b94da52414f82a.

* Consider using `validateString` to avoid unnecessary conversions. `validateBytes` accepts bytes to be able to detect and validate GLB. 
https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/075d6608a6b39a063f5e7cb329b94da52414f82a/server/src/server.ts#L132-L135
* Do we need to expose GLB-container-only validation API?
* Validator can report on broken JSON. If the intention is to avoid running validator on invalid input, this check should be done earlier.
https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/075d6608a6b39a063f5e7cb329b94da52414f82a/server/src/server.ts#L154-L157
* I'm not sure how TypeScript enums work, but reported `severity` integer values exactly match `DiagnosticSeverity` [definitions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DiagnosticSeverity). Maybe this `switch` isn't needed.
https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/075d6608a6b39a063f5e7cb329b94da52414f82a/server/src/server.ts#L198-L211
* `result` is an instance of some internal object, use `.toString()` to get readable representation. 
https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/075d6608a6b39a063f5e7cb329b94da52414f82a/server/src/server.ts#L169-L173

**Comment by emackey** [comment]
@lexaknyazev Thanks for the pre-PR review!  I do have plans to add a GLB validation command, especially now that VSCode itself can produce new GLB files, it's needed.  Perhaps newly-produced GLBs should auto-validate.  I'll look into the other comments here too.

**Comment by emackey** [comment]
@lexaknyazev Is there a way I can manually trigger the "Validator had problems" failure path?  Would like to test how VSCode handles those failures.

**Comment by lexaknyazev** [comment]
Try to feed it with nor glTF, neither GLB data.
